### ISSUE TITLE
-1 returned for struct with a func

### ISSUE THREAD

**Issue by christarazi** [DmitriyVTitov/size#12]
I was trying to print the size of the LRU cache variable from https://github.com/golang/groupcache/blob/41bb18bfe9da5321badc438f91158cd790a33aa3/lru/lru.go#L30.

```go
// Cache is an LRU cache. It is not safe for concurrent access.
type Cache struct {
	// MaxEntries is the maximum number of cache entries before
	// an item is evicted. Zero means no limit.
	MaxEntries int

	// OnEvicted optionally specifies a callback function to be
	// executed when an entry is purged from the cache.
	OnEvicted func(key Key, value interface{})

	ll    *list.List
	cache map[interface{}]*list.Element
}
```

But it returns -1 for this struct due the `OnEvicted` field.

**Comment by DmitriyVTitov** [comment]
Hi @christarazi 
Fixed in v1.5.0. Use this tag in your `go.mod` file.
Is the problem solved?

**Comment by christarazi** [comment]
Yes, thank you! It's worth adding a test case with the func set IMO and asserting that it's the same size as a pointer as well.

**Comment by DmitriyVTitov** [comment]
Well good point, but I use built-in func from reflect package to return the size of func-type value. First rule of testing is one shouldn't test the standard library :)
