### ISSUE TITLE
Negative size for tree struct

### ISSUE THREAD

**Issue by Xeoncross** [DmitriyVTitov/size#9]
I ran across a [negatively sized struct](https://github.com/gbrlsnchs/patricia/blob/master/tree.go#L6-L20) with multiple fields which you can see here: https://go.dev/play/p/z0IHBpxSeZe

```
import (
	"testing"

	"github.com/DmitriyVTitov/size"
	"github.com/gbrlsnchs/patricia"
)

func TestPatricia(t *testing.T) {
	trie := patricia.New("a")
	for i, w := range []string{"a", "b", "c"} {
		trie.Add(w, i)
	}

	t.Logf("size: %d\n", size.Of(trie)) // size: -1
}
```

**Comment by DmitriyVTitov** [comment]
Hi! This is probably because your IDE did not import latest version of my package.
To use latest tag v1.3.0 you should add this to `go.mod` file in your project:
```
require (
	...
	github.com/DmitriyVTitov/size v1.3.0
	...
```

Now your example gives:
```
=== RUN   TestPatricia
    main_test.go:16: size:        944
--- PASS: TestPatricia (0.00s)
PASS
```

**Comment by DmitriyVTitov** [comment]
I close the issue, but feel free to write me if you don't succeed.
